name: Deploy infrastructure

on:
  workflow_dispath:
  push:
    branches:
      - main
    paths:
      - 'terraform/**'
      - 'backend/**'

jobs:
  plan-changes:
    name: Review infrastructure changes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Terraform Init
        run: |
          cd terraform
          terraform init -input=false

      - name: Terraform Plan
        run: terraform plan -out=tfplan -input=false

  deploy-infra:
    name: Deploy infrastructure
    runs-on: ubuntu-latest
    environment: production
    needs: plan-changes
    steps:
      - name: Terraform Apply
        run: |
          cd terraform
          terraform apply -input=false -auto-approve tfplan
