name: Terraform PR Check

on:
  workflow_dispatch:
  pull_request:
    path:
      - .github/workflows/verify-pr.yaml
      - terraform/**

permissions:
  contents: read
  pull-requests: write
  id-token: write

jobs:
  verify-terraform:
    name: Verify Terraform
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Terraform Init
        run: terraform init
        env:
          AWS_REGION: {{ vars.AWS_REGION }}

      - name: Terraform Format Check
        run: terraform fmt -check

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -no-color | tee plan.txt

      - name: Comment PR with Terraform Plan
        uses: mshick/add-pr-comment@v2
        with:
          message: |
            ### Terraform Plan 🏗️
            ```
            $(cat plan.txt)
            ```
          repo-token: ${{ secrets.GITHUB_TOKEN }}
